// ============================================================================
// Sve države svijeta (ISO 3166-1 alpha-2), sa nazivima na bosanskom i
// engleskom. Spisak je generisan iz ICU podataka ugrađenih u Node (Intl.
// DisplayNames), pa su nazivi standardizovani, a ne ručno kucani.
//
// Izostavljeni su kodovi koji nisu države: nadnacionalni (EU, UN), tehnički i
// rezervisani (ZZ, XA, QO...), povučeni (YU, SU, CS...) i nenaseljene
// teritorije bez stalnog stanovništva (Antarktik, Bouvetovo ostrvo...).
//
// Poredak je abecedni po bosanskom nazivu. Za pojedine države ICU koristi
// hrvatski oblik ili skraćenicu, pa su ti nazivi ručno usklađeni sa
// uobičajenim bosanskim (Holandija, Velika Britanija, Palestina...).
// ============================================================================

export const SVE_DRZAVE = [
  { code: "AF", bs: "Afganistan", en: "Afghanistan" },
  { code: "AL", bs: "Albanija", en: "Albania" },
  { code: "DZ", bs: "Alžir", en: "Algeria" },
  { code: "VI", bs: "Američka Djevičanska ostrva", en: "U.S. Virgin Islands" },
  { code: "AS", bs: "Američka Samoa", en: "American Samoa" },
  { code: "AD", bs: "Andora", en: "Andorra" },
  { code: "AO", bs: "Angola", en: "Angola" },
  { code: "AI", bs: "Angvila", en: "Anguilla" },
  { code: "AG", bs: "Antigva i Barbuda", en: "Antigua & Barbuda" },
  { code: "AR", bs: "Argentina", en: "Argentina" },
  { code: "AM", bs: "Armenija", en: "Armenia" },
  { code: "AW", bs: "Aruba", en: "Aruba" },
  { code: "AU", bs: "Australija", en: "Australia" },
  { code: "AT", bs: "Austrija", en: "Austria" },
  { code: "AZ", bs: "Azerbejdžan", en: "Azerbaijan" },
  { code: "BS", bs: "Bahami", en: "Bahamas" },
  { code: "BH", bs: "Bahrein", en: "Bahrain" },
  { code: "BD", bs: "Bangladeš", en: "Bangladesh" },
  { code: "BB", bs: "Barbados", en: "Barbados" },
  { code: "BE", bs: "Belgija", en: "Belgium" },
  { code: "BZ", bs: "Belize", en: "Belize" },
  { code: "BJ", bs: "Benin", en: "Benin" },
  { code: "DY", bs: "Benin", en: "Benin" },
  { code: "BM", bs: "Bermuda", en: "Bermuda" },
  { code: "BY", bs: "Bjelorusija", en: "Belarus" },
  { code: "BW", bs: "Bocvana", en: "Botswana" },
  { code: "BO", bs: "Bolivija", en: "Bolivia" },
  { code: "BA", bs: "Bosna i Hercegovina", en: "Bosnia & Herzegovina" },
  { code: "CX", bs: "Božićno ostrvo", en: "Christmas Island" },
  { code: "BR", bs: "Brazil", en: "Brazil" },
  { code: "VG", bs: "Britanska Djevičanska ostrva", en: "British Virgin Islands" },
  { code: "IO", bs: "Britanska Teritorija u Indijskom Okeanu", en: "British Indian Ocean Territory" },
  { code: "BN", bs: "Brunej", en: "Brunei" },
  { code: "BG", bs: "Bugarska", en: "Bulgaria" },
  { code: "BF", bs: "Burkina Faso", en: "Burkina Faso" },
  { code: "HV", bs: "Burkina Faso", en: "Burkina Faso" },
  { code: "BI", bs: "Burundi", en: "Burundi" },
  { code: "BT", bs: "Butan", en: "Bhutan" },
  { code: "CF", bs: "Centralnoafrička Republika", en: "Central African Republic" },
  { code: "ME", bs: "Crna Gora", en: "Montenegro" },
  { code: "TD", bs: "Čad", en: "Chad" },
  { code: "CZ", bs: "Češka", en: "Czechia" },
  { code: "CL", bs: "Čile", en: "Chile" },
  { code: "DK", bs: "Danska", en: "Denmark" },
  { code: "CD", bs: "Demokratska Republika Kongo", en: "Congo - Kinshasa" },
  { code: "DM", bs: "Dominika", en: "Dominica" },
  { code: "DO", bs: "Dominikanska Republika", en: "Dominican Republic" },
  { code: "DJ", bs: "Džibuti", en: "Djibouti" },
  { code: "EG", bs: "Egipat", en: "Egypt" },
  { code: "EC", bs: "Ekvador", en: "Ecuador" },
  { code: "GQ", bs: "Ekvatorijalna Gvineja", en: "Equatorial Guinea" },
  { code: "ER", bs: "Eritreja", en: "Eritrea" },
  { code: "EE", bs: "Estonija", en: "Estonia" },
  { code: "SZ", bs: "Esvatini", en: "Eswatini" },
  { code: "ET", bs: "Etiopija", en: "Ethiopia" },
  { code: "FO", bs: "Farska ostrva", en: "Faroe Islands" },
  { code: "FJ", bs: "Fidži", en: "Fiji" },
  { code: "PH", bs: "Filipini", en: "Philippines" },
  { code: "FI", bs: "Finska", en: "Finland" },
  { code: "FK", bs: "Folklandska ostrva", en: "Falkland Islands" },
  { code: "FR", bs: "Francuska", en: "France" },
  { code: "GF", bs: "Francuska Gvajana", en: "French Guiana" },
  { code: "PF", bs: "Francuska Polinezija", en: "French Polynesia" },
  { code: "GA", bs: "Gabon", en: "Gabon" },
  { code: "GM", bs: "Gambija", en: "Gambia" },
  { code: "GH", bs: "Gana", en: "Ghana" },
  { code: "GI", bs: "Gibraltar", en: "Gibraltar" },
  { code: "GR", bs: "Grčka", en: "Greece" },
  { code: "GD", bs: "Grenada", en: "Grenada" },
  { code: "GL", bs: "Grenland", en: "Greenland" },
  { code: "GE", bs: "Gruzija", en: "Georgia" },
  { code: "GU", bs: "Guam", en: "Guam" },
  { code: "GG", bs: "Guernsey", en: "Guernsey" },
  { code: "GP", bs: "Gvadalupe", en: "Guadeloupe" },
  { code: "GY", bs: "Gvajana", en: "Guyana" },
  { code: "GT", bs: "Gvatemala", en: "Guatemala" },
  { code: "GN", bs: "Gvineja", en: "Guinea" },
  { code: "GW", bs: "Gvineja-Bisao", en: "Guinea-Bissau" },
  { code: "HT", bs: "Haiti", en: "Haiti" },
  { code: "NL", bs: "Holandija", en: "Netherlands" },
  { code: "HN", bs: "Honduras", en: "Honduras" },
  { code: "HK", bs: "Hong Kong (SAR Kina)", en: "Hong Kong SAR China" },
  { code: "HR", bs: "Hrvatska", en: "Croatia" },
  { code: "IN", bs: "Indija", en: "India" },
  { code: "ID", bs: "Indonezija", en: "Indonesia" },
  { code: "IQ", bs: "Irak", en: "Iraq" },
  { code: "IR", bs: "Iran", en: "Iran" },
  { code: "IE", bs: "Irska", en: "Ireland" },
  { code: "IS", bs: "Island", en: "Iceland" },
  { code: "TL", bs: "Istočni Timor", en: "Timor-Leste" },
  { code: "TP", bs: "Istočni Timor", en: "Timor-Leste" },
  { code: "IT", bs: "Italija", en: "Italy" },
  { code: "IL", bs: "Izrael", en: "Israel" },
  { code: "JM", bs: "Jamajka", en: "Jamaica" },
  { code: "JP", bs: "Japan", en: "Japan" },
  { code: "YD", bs: "Jemen", en: "Yemen" },
  { code: "YE", bs: "Jemen", en: "Yemen" },
  { code: "JE", bs: "Jersey", en: "Jersey" },
  { code: "JO", bs: "Jordan", en: "Jordan" },
  { code: "KR", bs: "Južna Koreja", en: "South Korea" },
  { code: "SS", bs: "Južni Sudan", en: "South Sudan" },
  { code: "ZA", bs: "Južnoafrička Republika", en: "South Africa" },
  { code: "KY", bs: "Kajmanska ostrva", en: "Cayman Islands" },
  { code: "KH", bs: "Kambodža", en: "Cambodia" },
  { code: "CM", bs: "Kamerun", en: "Cameroon" },
  { code: "CA", bs: "Kanada", en: "Canada" },
  { code: "BQ", bs: "Karipska Holandija", en: "Caribbean Netherlands" },
  { code: "QA", bs: "Katar", en: "Qatar" },
  { code: "KZ", bs: "Kazahstan", en: "Kazakhstan" },
  { code: "KE", bs: "Kenija", en: "Kenya" },
  { code: "CN", bs: "Kina", en: "China" },
  { code: "CY", bs: "Kipar", en: "Cyprus" },
  { code: "KG", bs: "Kirgistan", en: "Kyrgyzstan" },
  { code: "KI", bs: "Kiribati", en: "Kiribati" },
  { code: "CC", bs: "Kokosova (Keelingova) ostrva", en: "Cocos (Keeling) Islands" },
  { code: "CO", bs: "Kolumbija", en: "Colombia" },
  { code: "KM", bs: "Komori", en: "Comoros" },
  { code: "XK", bs: "Kosovo", en: "Kosovo" },
  { code: "CR", bs: "Kostarika", en: "Costa Rica" },
  { code: "CU", bs: "Kuba", en: "Cuba" },
  { code: "CK", bs: "Kukova ostrva", en: "Cook Islands" },
  { code: "CW", bs: "Kurasao", en: "Curaçao" },
  { code: "KW", bs: "Kuvajt", en: "Kuwait" },
  { code: "LA", bs: "Laos", en: "Laos" },
  { code: "LV", bs: "Latvija", en: "Latvia" },
  { code: "LS", bs: "Lesoto", en: "Lesotho" },
  { code: "LB", bs: "Liban", en: "Lebanon" },
  { code: "LR", bs: "Liberija", en: "Liberia" },
  { code: "LY", bs: "Libija", en: "Libya" },
  { code: "LI", bs: "Lihtenštajn", en: "Liechtenstein" },
  { code: "LT", bs: "Litvanija", en: "Lithuania" },
  { code: "LU", bs: "Luksemburg", en: "Luxembourg" },
  { code: "MG", bs: "Madagaskar", en: "Madagascar" },
  { code: "HU", bs: "Mađarska", en: "Hungary" },
  { code: "YT", bs: "Majote", en: "Mayotte" },
  { code: "MO", bs: "Makao (SAR Kina)", en: "Macao SAR China" },
  { code: "MW", bs: "Malavi", en: "Malawi" },
  { code: "MV", bs: "Maldivi", en: "Maldives" },
  { code: "MY", bs: "Malezija", en: "Malaysia" },
  { code: "ML", bs: "Mali", en: "Mali" },
  { code: "MT", bs: "Malta", en: "Malta" },
  { code: "MA", bs: "Maroko", en: "Morocco" },
  { code: "MH", bs: "Maršalova ostrva", en: "Marshall Islands" },
  { code: "MQ", bs: "Martinik", en: "Martinique" },
  { code: "MU", bs: "Mauricijus", en: "Mauritius" },
  { code: "MR", bs: "Mauritanija", en: "Mauritania" },
  { code: "MX", bs: "Meksiko", en: "Mexico" },
  { code: "MM", bs: "Mijanmar", en: "Myanmar (Burma)" },
  { code: "FM", bs: "Mikronezija", en: "Micronesia" },
  { code: "MD", bs: "Moldavija", en: "Moldova" },
  { code: "MC", bs: "Monako", en: "Monaco" },
  { code: "MN", bs: "Mongolija", en: "Mongolia" },
  { code: "MS", bs: "Monserat", en: "Montserrat" },
  { code: "MZ", bs: "Mozambik", en: "Mozambique" },
  { code: "NA", bs: "Namibija", en: "Namibia" },
  { code: "NR", bs: "Nauru", en: "Nauru" },
  { code: "NP", bs: "Nepal", en: "Nepal" },
  { code: "NE", bs: "Niger", en: "Niger" },
  { code: "NG", bs: "Nigerija", en: "Nigeria" },
  { code: "NI", bs: "Nikaragva", en: "Nicaragua" },
  { code: "NU", bs: "Niue", en: "Niue" },
  { code: "NO", bs: "Norveška", en: "Norway" },
  { code: "NC", bs: "Nova Kaledonija", en: "New Caledonia" },
  { code: "NZ", bs: "Novi Zeland", en: "New Zealand" },
  { code: "DE", bs: "Njemačka", en: "Germany" },
  { code: "CI", bs: "Obala Slonovače", en: "Côte d’Ivoire" },
  { code: "AX", bs: "Olandska ostrva", en: "Åland Islands" },
  { code: "OM", bs: "Oman", en: "Oman" },
  { code: "TC", bs: "Ostrva Turks i Kaikos", en: "Turks & Caicos Islands" },
  { code: "WF", bs: "Ostrva Valis i Futuna", en: "Wallis & Futuna" },
  { code: "IM", bs: "Ostrvo Man", en: "Isle of Man" },
  { code: "NF", bs: "Ostrvo Norfolk", en: "Norfolk Island" },
  { code: "PK", bs: "Pakistan", en: "Pakistan" },
  { code: "PW", bs: "Palau", en: "Palau" },
  { code: "PS", bs: "Palestina", en: "Palestinian Territories" },
  { code: "PA", bs: "Panama", en: "Panama" },
  { code: "PG", bs: "Papua Nova Gvineja", en: "Papua New Guinea" },
  { code: "PY", bs: "Paragvaj", en: "Paraguay" },
  { code: "PE", bs: "Peru", en: "Peru" },
  { code: "PN", bs: "Pitkernska Ostrva", en: "Pitcairn Islands" },
  { code: "PL", bs: "Poljska", en: "Poland" },
  { code: "PR", bs: "Porto Riko", en: "Puerto Rico" },
  { code: "PT", bs: "Portugal", en: "Portugal" },
  { code: "CG", bs: "Republika Kongo", en: "Congo - Brazzaville" },
  { code: "RE", bs: "Reunion", en: "Réunion" },
  { code: "RW", bs: "Ruanda", en: "Rwanda" },
  { code: "RO", bs: "Rumunija", en: "Romania" },
  { code: "RU", bs: "Rusija", en: "Russia" },
  { code: "SV", bs: "Salvador", en: "El Salvador" },
  { code: "WS", bs: "Samoa", en: "Samoa" },
  { code: "SM", bs: "San Marino", en: "San Marino" },
  { code: "ST", bs: "Sao Tome i Principe", en: "São Tomé & Príncipe" },
  { code: "SA", bs: "Saudijska Arabija", en: "Saudi Arabia" },
  { code: "SC", bs: "Sejšeli", en: "Seychelles" },
  { code: "SN", bs: "Senegal", en: "Senegal" },
  { code: "SL", bs: "Sijera Leone", en: "Sierra Leone" },
  { code: "SG", bs: "Singapur", en: "Singapore" },
  { code: "SX", bs: "Sint Marten", en: "Sint Maarten" },
  { code: "SY", bs: "Sirija", en: "Syria" },
  { code: "US", bs: "Sjedinjene Američke Države", en: "United States" },
  { code: "KP", bs: "Sjeverna Koreja", en: "North Korea" },
  { code: "MK", bs: "Sjeverna Makedonija", en: "North Macedonia" },
  { code: "MP", bs: "Sjeverna Marijanska ostrva", en: "Northern Mariana Islands" },
  { code: "SK", bs: "Slovačka", en: "Slovakia" },
  { code: "SI", bs: "Slovenija", en: "Slovenia" },
  { code: "SB", bs: "Solomonska Ostrva", en: "Solomon Islands" },
  { code: "SO", bs: "Somalija", en: "Somalia" },
  { code: "RS", bs: "Srbija", en: "Serbia" },
  { code: "SD", bs: "Sudan", en: "Sudan" },
  { code: "SR", bs: "Surinam", en: "Suriname" },
  { code: "SJ", bs: "Svalbard i Jan Mayen", en: "Svalbard & Jan Mayen" },
  { code: "SH", bs: "Sveta Helena", en: "St. Helena" },
  { code: "LC", bs: "Sveta Lucija", en: "St. Lucia" },
  { code: "BL", bs: "Sveti Bartolomej", en: "St. Barthélemy" },
  { code: "KN", bs: "Sveti Kits i Nevis", en: "St. Kitts & Nevis" },
  { code: "MF", bs: "Sveti Martin", en: "St. Martin" },
  { code: "PM", bs: "Sveti Petar i Mikelon", en: "St. Pierre & Miquelon" },
  { code: "VC", bs: "Sveti Vinsent i Grenadin", en: "St. Vincent & Grenadines" },
  { code: "ES", bs: "Španija", en: "Spain" },
  { code: "LK", bs: "Šri Lanka", en: "Sri Lanka" },
  { code: "SE", bs: "Švedska", en: "Sweden" },
  { code: "CH", bs: "Švicarska", en: "Switzerland" },
  { code: "TJ", bs: "Tadžikistan", en: "Tajikistan" },
  { code: "TH", bs: "Tajland", en: "Thailand" },
  { code: "TW", bs: "Tajvan", en: "Taiwan" },
  { code: "TZ", bs: "Tanzanija", en: "Tanzania" },
  { code: "TG", bs: "Togo", en: "Togo" },
  { code: "TK", bs: "Tokelau", en: "Tokelau" },
  { code: "TO", bs: "Tonga", en: "Tonga" },
  { code: "TT", bs: "Trinidad i Tobago", en: "Trinidad & Tobago" },
  { code: "TN", bs: "Tunis", en: "Tunisia" },
  { code: "TM", bs: "Turkmenistan", en: "Turkmenistan" },
  { code: "TR", bs: "Turska", en: "Türkiye" },
  { code: "TV", bs: "Tuvalu", en: "Tuvalu" },
  { code: "UG", bs: "Uganda", en: "Uganda" },
  { code: "AE", bs: "Ujedinjeni Arapski Emirati", en: "United Arab Emirates" },
  { code: "UK", bs: "Ujedinjeno Kraljevstvo", en: "United Kingdom" },
  { code: "UA", bs: "Ukrajina", en: "Ukraine" },
  { code: "UY", bs: "Urugvaj", en: "Uruguay" },
  { code: "UZ", bs: "Uzbekistan", en: "Uzbekistan" },
  { code: "NH", bs: "Vanuatu", en: "Vanuatu" },
  { code: "VU", bs: "Vanuatu", en: "Vanuatu" },
  { code: "VA", bs: "Vatikan", en: "Vatican City" },
  { code: "GB", bs: "Velika Britanija", en: "United Kingdom" },
  { code: "VE", bs: "Venecuela", en: "Venezuela" },
  { code: "VD", bs: "Vijetnam", en: "Vietnam" },
  { code: "VN", bs: "Vijetnam", en: "Vietnam" },
  { code: "ZM", bs: "Zambija", en: "Zambia" },
  { code: "EH", bs: "Zapadna Sahara", en: "Western Sahara" },
  { code: "CV", bs: "Zelenortska Ostrva", en: "Cape Verde" },
  { code: "RH", bs: "Zimbabve", en: "Zimbabwe" },
  { code: "ZW", bs: "Zimbabve", en: "Zimbabwe" },
]

// Države koje se najčešće biraju - Bosna i Hercegovina, susjedne zemlje i
// zemlje sa najbrojnijom bosanskom dijasporom. Prikazuju se na vrhu spiska da
// korisnik ne mora skrolati kroz 250 stavki.
export const CESTE_DRZAVE = ["BA", "HR", "RS", "ME", "SI", "MK", "DE", "AT", "CH", "SE", "NO", "DK", "NL", "US", "TR"]
